# Generated by Django 4.1.7 on 2023-02-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
